py_test(
    name = "attn_factory_prefill_cuda_graph_test",
    srcs = ["attn_factory_prefill_cuda_graph_test.py"],
    deps = [
        "//rtp_llm/models_py/standalone:py_standalone_testlib",
    ],
)
